spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lotApiServer
  profiles:
    #active: @package.environment@
    active: dev
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC
  #提供畫面內容
  mvc:
    view:
      prefix: /
      suffix: .html
  #view:
  #  prefix: /
  #  suffix: .html
  session:
#    store-type: jdbc
#    jdbc:
#      initialize-schema: always
    timeout:
      seconds: 900
  port: ${port:8080}
  compression:
    enabled: true
server:
  error:
    whitelabel:
      enabled: false
    path: /error
jwt:
  secret: mypartySecret